### ISSUE TITLE
space-after-colon hates pseudo class selectors in nested LESS

### ISSUE THREAD

**Issue by kaleb** [csscomb/csscomb.js#309] opened 2014-09-09 21:01 UTC
Input:

```
.broken {          
    a:hover {              
        color: #fff;
    }              
}                  
```

After:

```
.broken             
{
    a: hover        
    {               
        color: #fff;
    }               
}                   
```

Look at the space after `a:`.
##

**Comment by sadsat** [comment] 2015-04-16 16:32
I can confirm this for csscomb-grunt.

A workaround seems to be the usage of another nesting level:

```
.module {
    article {
        &:last-child {
           ... 
        }
    }
}
```

**Comment by maxfenton** [comment] 2015-05-13 15:24
+1

**Comment by SpencerCarstens** [comment] 2015-08-10 22:16
+1

Found this the hard way today.

**Comment by ganchan** [comment] 2015-11-25 12:58
I've noticed that this do not happen when you use this syntax
```less
li
{
  &:last-child
  {
  // some styles
  }
}

**Comment by Kepro** [comment] 2015-11-30 08:31
easy way to fix it just set "space-after-colon": 0,

**Comment by maxfenton** [comment] 2015-11-30 16:09
`easy way to fix it just set "space-after-colon": 0,` — that's actually a good help towards seeing where the problem is, @kepro 

Thanks.

**Comment by Buzut** [comment] 2016-11-14 00:24
Is this fixed? csscomb 3.1.7 with gulp-csscomb 3.0.8 here and I still have the bug. Culprit code:

```css
#menu {
    padding: 0;
    margin: 0;

    .navlinks {
        margin-top: 5px;

        // HERE (adds a space after "a:")
        a:last-child {
            padding-left: 14px;
            margin-left: 12px;
            content: "";
            border-left: 1px solid #273041;
        }
    }

    .menuicons {
        margin-top: 8px;

        .icon {
            float: right;
            margin-left: 10px;
            cursor: pointer;
        }
    }
}
```

**Comment by boneyfantaseas** [comment] 2016-11-18 08:28
Label status:fixed is false, issue is still open. I have this issue using sublime-csscomb.

**Comment by jdalton** [comment] 2019-05-06 06:56
This is fixed in the latest csscomb release :D

**Closed by jdalton** 2019-05-06 06:56 UTC
Labels: category: gpe, status: fixed, type: bug
