### ISSUE TITLE
Add a space between styles and subclasses

### ISSUE THREAD

**Issue by danilvalov** [csscomb/csscomb.js#441] opened 2015-12-21 11:30 UTC
I have a code:

```
.class {
  width: 100px;
  height: 100px;
  .subclass {
    color: red;
  }
}
```

I want add a space between `height: 100px;` and `.subclass {`.

Example:

```
.class {
  width: 100px;
  height: 100px;
                                      <- indent
  .subclass {
    color: red;
  }
}
```

Can I do it?
##

**Comment by VictorCamargo** [comment] 2016-01-14 12:31
+1

**Comment by dsongman** [comment] 2016-02-03 23:00
+1

**Comment by vincentaudebert** [comment] 2016-04-15 03:35
I think this is a duplicate of https://github.com/csscomb/csscomb.js/issues/210
And there is a PR for this: https://github.com/csscomb/csscomb.js/pull/405

It is currently on dev branch.

**Comment by VictorCamargo** [comment] 2016-04-15 09:05
@vincentaudebert Didn't see this before, really thank you.

**Comment by VictorCamargo** [comment] 2016-04-15 10:29
@vincentaudebert, sorry for that but, I did not set this up. Can you help me use it?

**Comment by jdalton** [comment] 2019-04-26 05:10
Closed by #436.

**Closed by jdalton** 2019-04-26 05:10 UTC
Labels: type: enhancement
