### ISSUE TITLE
SCSS code sample generates a Gonzales PE error

### ISSUE THREAD

**Issue by prettydiff** [csscomb/csscomb.js#481] opened 2016-08-10 16:51 UTC
https://github.com/Glavin001/atom-beautify/issues/1129
##

**Comment by tomagladiator** [comment] 2016-08-14 06:46
I find this too, csscomb doesn't like [interpolation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_):
```
.bg-#{$color} {
    ...
}
```

**Comment by sergey-kozlov** [comment] 2016-11-14 12:28
Please check the validity of the block starting from line #13

11 |     &__content {
12 |         @include fading-show('hidden');
13*|         margin: $gutter-half #{-$gutter-half} 0;
14 |         padding: $gutter-half;
15 |         background: $contentColor;

Gonzales PE version: 3.0.0-28
Syntax: scss
CSScomb Core version: 3.0.0-3

This is CSScomb or Gonzales bug?

**Comment by thejamespower** [comment] 2017-01-31 11:27
CSSComb bug caused by an outdated version of Gonzales. See [here](https://github.com/tonyganch/gonzales-pe/issues/243).

**Comment by jdalton** [comment] 2019-05-06 06:18
This should be fixed with the latest release 🎉

**Closed by jdalton** 2019-05-06 06:18 UTC
Labels: category: gpe, status: fixed
