### ISSUE TITLE
Variable interpolation doesn't seem to work for property name

### ISSUE THREAD

**Issue by lokywin** [csscomb/csscomb.js#426] opened 2015-09-21 20:27 UTC
```
div {
    margin-#{$direction}: 20px;    
    top: 0;  
}
```
Use case: `$direction: right` for right to left language such as Arabic.

**Comment by habovh** [comment] 2016-03-31 15:40
When will the fix be available on `master`?

**Comment by tonyganch** [comment] 2016-07-11 23:44
Hi guys, the issue is fixed in the latest release of csscomb.

**Closed by tonyganch** 2016-07-11 23:44 UTC
Labels: fixed in dev

**Comment by chenby** [comment] 2018-03-11 08:14
```css
.variable(@attributes,@px) {
    @{attributes}: @px;
};
.b {
    .variable(width, 20);
}
```
it doesn't work in less.
