### ISSUE TITLE
LESS support @{b}

### ISSUE THREAD

**Issue by xaolas** [csscomb/csscomb.js#403] opened 2015-07-01 14:34 UTC
You can help me with this?
Error: Please check the validity of the block starting from line #2:

    &{@b:~".sub";
        @{b} {
            margin-bottom: 50px;
            text-align: center;
        }
    
        @{b}__title {
            padding: 40px 0 45px;
            position: relative;
            display: block;
            text-decoration: none;
            color: #fff;
            font-size: 65px;
            font-weight: bold;
            color: #fff;
            line-height: 1.1;
    
            &:before {
                content: "";
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                background: fade(@color-main, 94%);
            }
        }
    
        @{b}__nav {
            background: @color-bg;
            color: #fff;
            padding: 5px 5px 6px;
            font-size: 16px;
            font-weight: 600;
    
            &-item {
                color: #fff;
                text-decoration: none;
                padding: 3px 15px;
                display: inline-block;
    
                @media (max-width: @screen-sm-max) {
                    padding: 5px 10px;
                }
    
                &:hover, &_active {
                    color: @color-main;
                }
            }
        }
    }

**Comment by tonyganch** [comment] 2016-07-11 23:35
Hi, it seems like the issue is fixed with the latest version of csscomb.

**Closed by tonyganch** 2016-07-11 23:35 UTC
Labels: fixed in dev, gonzales
