### ISSUE TITLE
Error on scss interpolation

### ISSUE THREAD

**Issue by Ebulavina** [csscomb/csscomb.js#474] opened 2016-07-21 08:42 UTC
Parsing error: Please check the validity of the block starting from line #5

3 | .gallery {
4 |   left: -$gutter;
5*|   width: calc(100% + #{$gutter * 2});
6 |   height: 100%;
7 |   margin: 30px 0;

Gonzales PE version: 3.0.0-28
Syntax: scss

**Comment by mkhazov** [comment] 2016-07-23 14:22
The problem is csscomb.js v3.1.7 uses the old version of gonzales-pe

**Comment by tonyganch** [comment] 2016-08-03 19:59
Fixed in dev, will be released as version 4.0

**Closed by tonyganch** 2016-08-03 19:59 UTC

**Comment by brianmilner** [comment] 2016-11-09 20:50
Any updates on when this will be released offically? I could use the fix for this. Thanks
